/* This is a GENERATED file. */
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __GWYDDION_TYPES_H__
#define __GWYDDION_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType gwy_si_unit_format_style_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_SI_UNIT_FORMAT_STYLE (gwy_si_unit_format_style_get_type())
GType gwy_nl_fit_param_flags_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_NL_FIT_PARAM_FLAGS (gwy_nl_fit_param_flags_get_type())
GType gwy_percentile_interpolation_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_PERCENTILE_INTERPOLATION_TYPE (gwy_percentile_interpolation_type_get_type())
GType gwy_expr_error_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_EXPR_ERROR (gwy_expr_error_get_type())
GType gwy_results_value_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RESULTS_VALUE_TYPE (gwy_results_value_type_get_type())
GType gwy_results_report_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RESULTS_REPORT_TYPE (gwy_results_report_type_get_type())
GType gwy_raw_data_type_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_RAW_DATA_TYPE (gwy_raw_data_type_get_type())
GType gwy_byte_order_get_type(void) G_GNUC_CONST;
#define GWY_TYPE_BYTE_ORDER (gwy_byte_order_get_type())
G_END_DECLS

#endif /* __GWYDDION_TYPES_H__ */

/* Generated data ends here */

